using System.ComponentModel;

namespace SAM.Analytical.Systems
{
    [Description("Curve Modifier Variable Type")]
    public enum CurveModifierVariableType
    {
        [Description("ODB")] ODB,
        [Description("OHumRat")] OHumRat,
        [Description("ORH")] ORH,
        [Description("OWB")] OWB,
        [Description("OEnthalpy")] OEnthalpy,
        [Description("OPollutant")] OPollutant,
        [Description("EDB")] EDB,
        [Description("EHumRat")] EHumRat,
        [Description("ERH")] ERH,
        [Description("EWB")] EWB,
        [Description("EEnthalpy")] EEnthalpy,
        [Description("EPollutant")] EPollutant,
        [Description("EFlow")] EFlow,
        [Description("EDB2")] EDB2,
        [Description("EHumRat2")] EHumRat2,
        [Description("ERH2")] ERH2,
        [Description("EWB2")] EWB2,
        [Description("EEnthalpy2")] EEnthalpy2,
        [Description("EPollutant2")] EPollutant2,
        [Description("EFlow2")] EFlow2,
        [Description("WTemp")] WTemp,
        [Description("WFlow")] WFlow,
        [Description("WTemp2")] WTemp2,
        [Description("WFlow2")] WFlow2,
        [Description("Partload")] Partload,
        [Description("Demand")] Demand,
        [Description("Irradiance")] Irradiance,
        [Description("Area")] Area,
        [Description("WindSpeed")] WindSpeed,
        [Description("WindDirection")] WindDirection,
        [Description("RPipeLength")] RPipeLength,
        [Description("TotalInternal")] TotalInternal,
        [Description("DeltaT")] DeltaT,
        [Description("TotalIntCap")] TotalIntCap,
        [Description("WTemp3")] WTemp3,
        [Description("WFlow3")] WFlow3,
        [Description("WPipeLength")] WPipeLength,
        [Description("HeatPartload")] HeatPartload,
        [Description("CoolPartload")] CoolPartload,
        [Description("ControlSignal")] ControlSignal,
        [Description("CloudCover")] CloudCover,
        [Description("DiffuseRadiation")] DiffuseRadiation,
        [Description("GlobalRadiation")] GlobalRadiation,
        [Description("OWaterTemp")] OWaterTemp,
        [Description("Load")] Load,
        [Description("LAST")] LAST,
    }
}
